// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/sacas/sacas/blob/main/LICENSE)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: sacas/incentives/v1/query.proto

package incentivesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Incentives_FullMethodName       = "/sacas.incentives.v1.Query/Incentives"
	Query_Incentive_FullMethodName        = "/sacas.incentives.v1.Query/Incentive"
	Query_GasMeters_FullMethodName        = "/sacas.incentives.v1.Query/GasMeters"
	Query_GasMeter_FullMethodName         = "/sacas.incentives.v1.Query/GasMeter"
	Query_AllocationMeters_FullMethodName = "/sacas.incentives.v1.Query/AllocationMeters"
	Query_AllocationMeter_FullMethodName  = "/sacas.incentives.v1.Query/AllocationMeter"
	Query_Params_FullMethodName           = "/sacas.incentives.v1.Query/Params"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Incentives retrieves registered incentives
	Incentives(ctx context.Context, in *QueryIncentivesRequest, opts ...grpc.CallOption) (*QueryIncentivesResponse, error)
	// Incentive retrieves a registered incentive
	Incentive(ctx context.Context, in *QueryIncentiveRequest, opts ...grpc.CallOption) (*QueryIncentiveResponse, error)
	// GasMeters retrieves active gas meters for a given contract
	GasMeters(ctx context.Context, in *QueryGasMetersRequest, opts ...grpc.CallOption) (*QueryGasMetersResponse, error)
	// GasMeter retrieves a active gas meter
	GasMeter(ctx context.Context, in *QueryGasMeterRequest, opts ...grpc.CallOption) (*QueryGasMeterResponse, error)
	// AllocationMeters retrieves active allocation meters for a given
	// denomination
	AllocationMeters(ctx context.Context, in *QueryAllocationMetersRequest, opts ...grpc.CallOption) (*QueryAllocationMetersResponse, error)
	// AllocationMeter retrieves a active gas meter
	AllocationMeter(ctx context.Context, in *QueryAllocationMeterRequest, opts ...grpc.CallOption) (*QueryAllocationMeterResponse, error)
	// Params retrieves the incentives module params
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Incentives(ctx context.Context, in *QueryIncentivesRequest, opts ...grpc.CallOption) (*QueryIncentivesResponse, error) {
	out := new(QueryIncentivesResponse)
	err := c.cc.Invoke(ctx, Query_Incentives_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Incentive(ctx context.Context, in *QueryIncentiveRequest, opts ...grpc.CallOption) (*QueryIncentiveResponse, error) {
	out := new(QueryIncentiveResponse)
	err := c.cc.Invoke(ctx, Query_Incentive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GasMeters(ctx context.Context, in *QueryGasMetersRequest, opts ...grpc.CallOption) (*QueryGasMetersResponse, error) {
	out := new(QueryGasMetersResponse)
	err := c.cc.Invoke(ctx, Query_GasMeters_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GasMeter(ctx context.Context, in *QueryGasMeterRequest, opts ...grpc.CallOption) (*QueryGasMeterResponse, error) {
	out := new(QueryGasMeterResponse)
	err := c.cc.Invoke(ctx, Query_GasMeter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllocationMeters(ctx context.Context, in *QueryAllocationMetersRequest, opts ...grpc.CallOption) (*QueryAllocationMetersResponse, error) {
	out := new(QueryAllocationMetersResponse)
	err := c.cc.Invoke(ctx, Query_AllocationMeters_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllocationMeter(ctx context.Context, in *QueryAllocationMeterRequest, opts ...grpc.CallOption) (*QueryAllocationMeterResponse, error) {
	out := new(QueryAllocationMeterResponse)
	err := c.cc.Invoke(ctx, Query_AllocationMeter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Incentives retrieves registered incentives
	Incentives(context.Context, *QueryIncentivesRequest) (*QueryIncentivesResponse, error)
	// Incentive retrieves a registered incentive
	Incentive(context.Context, *QueryIncentiveRequest) (*QueryIncentiveResponse, error)
	// GasMeters retrieves active gas meters for a given contract
	GasMeters(context.Context, *QueryGasMetersRequest) (*QueryGasMetersResponse, error)
	// GasMeter retrieves a active gas meter
	GasMeter(context.Context, *QueryGasMeterRequest) (*QueryGasMeterResponse, error)
	// AllocationMeters retrieves active allocation meters for a given
	// denomination
	AllocationMeters(context.Context, *QueryAllocationMetersRequest) (*QueryAllocationMetersResponse, error)
	// AllocationMeter retrieves a active gas meter
	AllocationMeter(context.Context, *QueryAllocationMeterRequest) (*QueryAllocationMeterResponse, error)
	// Params retrieves the incentives module params
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Incentives(context.Context, *QueryIncentivesRequest) (*QueryIncentivesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Incentives not implemented")
}
func (UnimplementedQueryServer) Incentive(context.Context, *QueryIncentiveRequest) (*QueryIncentiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Incentive not implemented")
}
func (UnimplementedQueryServer) GasMeters(context.Context, *QueryGasMetersRequest) (*QueryGasMetersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GasMeters not implemented")
}
func (UnimplementedQueryServer) GasMeter(context.Context, *QueryGasMeterRequest) (*QueryGasMeterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GasMeter not implemented")
}
func (UnimplementedQueryServer) AllocationMeters(context.Context, *QueryAllocationMetersRequest) (*QueryAllocationMetersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocationMeters not implemented")
}
func (UnimplementedQueryServer) AllocationMeter(context.Context, *QueryAllocationMeterRequest) (*QueryAllocationMeterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocationMeter not implemented")
}
func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Incentives_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIncentivesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Incentives(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Incentives_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Incentives(ctx, req.(*QueryIncentivesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Incentive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIncentiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Incentive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Incentive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Incentive(ctx, req.(*QueryIncentiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GasMeters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGasMetersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GasMeters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GasMeters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GasMeters(ctx, req.(*QueryGasMetersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GasMeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGasMeterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GasMeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GasMeter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GasMeter(ctx, req.(*QueryGasMeterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllocationMeters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllocationMetersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllocationMeters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllocationMeters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllocationMeters(ctx, req.(*QueryAllocationMetersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllocationMeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllocationMeterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllocationMeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllocationMeter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllocationMeter(ctx, req.(*QueryAllocationMeterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sacas.incentives.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Incentives",
			Handler:    _Query_Incentives_Handler,
		},
		{
			MethodName: "Incentive",
			Handler:    _Query_Incentive_Handler,
		},
		{
			MethodName: "GasMeters",
			Handler:    _Query_GasMeters_Handler,
		},
		{
			MethodName: "GasMeter",
			Handler:    _Query_GasMeter_Handler,
		},
		{
			MethodName: "AllocationMeters",
			Handler:    _Query_AllocationMeters_Handler,
		},
		{
			MethodName: "AllocationMeter",
			Handler:    _Query_AllocationMeter_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sacas/incentives/v1/query.proto",
}
